apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-all-secure-app
  namespace: secure-namespace
spec:
  podSelector:
    matchLabels:
      app: secure
  policyTypes:
    - Ingress
    - Egress
