apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuln
  template:
    metadata:
      labels:
        app: vuln
    spec:
      containers:
        - name: app
          image: nginx:latest
          ports:
            - containerPort: 80
          securityContext:
            runAsUser: 0                 # ❌ Runs as root
            allowPrivilegeEscalation: true  # ❌ Dangerous
          env:
            - name: PASSWORD
              value: "SuperSecret123"     # ❌ Hardcoded secret