  name: Kubescape Scan
  on: pull_request
  jobs:
    kubescape:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Kubescape Scan
          id: kubescape
          run: |
              echo "Installing Kubescape..."
              curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
              export PATH=$PATH:/home/runner/.kubescape/bin
              echo "Kubescape installation completed"
      
              echo "Starting Kubescape scan..."
              kubescape version
            
              kubescape scan --severity-threshold high --keep-local -l debug framework nsa,mitre,soc2,cis-eks-t1.2.0 . -v
              
        - name: Check Kubescape Results
            if: steps.kubescape.outcome == 'failure'
            run: |
              echo "::error::There is Critical or High findings detected that will block this PR until resolved. Please fix and re-run the workflow"
              exit 1