name: Kubescape Scan
on: pull_request
jobs:
  kubescape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kubescape Scan
        run: |
            echo "Installing Kubescape..."
            curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
            export PATH=$PATH:/home/runner/.kubescape/bin
            echo "Kubescape installation completed"
    
            echo "Starting Kubescape scan..."
            kubescape version
            
            # command to show the current working directory
            echo "Current working directory: $(pwd)"
            # show folder and files in the current working directory
            echo "Contents of the current directory:"
            ls -la $(pwd)
            
            # setting up the command
            COMMAND="kubescape scan"
            FRAMEWORKS="nsa,cis-eks-t1.2.0"
            LOG_LEVEL="-l error"
            $SCAN_DIR="."
            $COMMAND $LOG_LEVEL $FRAMEWORKS $SCAN_DIR