name: Kubescape scan
on: [pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Kubescape Scan
      uses: kubescape/github-action@main
      with:
        format: pretty-print
        verbose: on
        frameworks:
          nsa,mitre
    - name: Comment in PR
      if: always()
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        pr_number=${{ github.event.pull_request.number }}
        gh pr comment "$pr_number" --body-file results