name: Kubescape scan
on: [pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Kubescape Scan
      uses: kubescape/github-action@main
      with:
        format: sarif
        outputFile: results
        severityThreshold: high
        verbose: on
        frameworks:
          nsa,mitre
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        pr_number=${{ github.event.pull_request.number }}
        gh pr comment "$pr_number" --body-file result