name: Kubescape Scan
on: pull_request
jobs:
  kubescape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kubescape Scan
        run: |
            echo "Installing Kubescape..."
            curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
            echo "Kubescape installation completed"
    
            echo "Starting Kubescape scan..."
            
            # prepare command
            COMMAND="kubescape scan"
            FRAMEWORKS="nsa,cis-eks-t1.2.0"
            CURRENT_DIR=${{ github.event.repository.name }}
            LOG_LEVEL="-l error"
            $COMMAND LOG_LEVEL $FRAMEWORKS $CURRENT_DIR