name: Kubescape scan
on: [pull_request]
jobs:
  kubescape:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Kubescape Scan
      uses: kubescape/github-action@main
      continue-on-error: true
      with:
        format: sarif
        outputFile: results
        severityThreshold: high
        verbose: on
        frameworks:
          nsa,mitre