  name: Kubescape Scan
  on: pull_request
  jobs:
    kubescape:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Kubescape Scan
          id: kubescape
          run: |
              echo "Installing Kubescape..."
              curl -s https://raw.githubusercontent.com/kubescape/kubescape/master/install.sh | /bin/bash
              export PATH=$PATH:/home/runner/.kubescape/bin
              echo "Kubescape installation completed"
      
              echo "Starting Kubescape scan..."
              kubescape version
              
              set +e

              kubescape scan --severity-threshold high --keep-local -l debug framework nsa,mitre,soc2,cis-eks-t1.2.0 . -v
              EXIT_CODE=$?
              
              set -e

              if [ $EXIT_CODE -ne 0 ]; then
                echo "::error::❌ Kubescape scan failed due to high or critical findings."
                echo "Please review the scan results above and fix the issues before merging."
                exit $EXIT_CODE
              else
                echo "✅ Kubescape scan passed. No high or critical findings."
              fi